### ISSUE TITLE
Something wrong with password RegEx

### ISSUE THREAD

**Issue by bissleb** [awslabs/amazon-kinesis-data-generator#1]
When using the hosted Kinesis Data Generator, no matter what password I use, I still get a "Template validation error: Parameter Password failed to satisfy constraint: must be at least 6 alpha-numeric characters, and contain at least one number" error.

**Comment by bissleb** [comment]
Ugh, nevermind, I was trying to use non-alphanumeric characters.

**Comment by ayehia2000** [comment]
Actually this was helpful, thank you

**Comment by ritika26** [comment]
I am also facing the same problem. When using the hosted Kinesis Data Generator, no matter what password I use, I still get a "Template validation error: Parameter Password failed to satisfy constraint: must be at least 6 alpha-numeric characters, and contain at least one number"

Please tell how to fix the issue

**Comment by jsbach-jung** [comment]
This continues to perplex customers because the wording is not clear - it should say:

"Template validation error: Parameter Password failed to satisfy constraint: must be at least 6 alpha-numeric characters, and contain at least one number, and CANNOT contain special characters."

Once I removed my special character it went through.
