### ISSUE TITLE
JSON get's converted to Base64

### ISSUE THREAD

**Issue by trahloff** [awslabs/amazon-kinesis-data-generator#5]
When sending the record template 

```json
{
	"sensorId": 40,
	"currentTemperature": 76,
	"status": "OK"
}
```
the payload delivered to Kinesis is Base64 encoded.

```json
{
    "kinesis": {
        "kinesisSchemaVersion": "1.0",
        "partitionKey": "2264290559",
        "sequenceNumber": "49583841783469136626947675794180856103183100390328500226",
        "data": "ewkic2Vuc29ySWQiOiA0MCwJImN1cnJlbnRUZW1wZXJhdHVyZSI6IDc2LAkic3RhdHVzIjogIk9LIn0K",
        "approximateArrivalTimestamp": 1524572040.471
    },
    "eventSource": "aws:kinesis",
    "eventVersion": "1.0",
    "eventID": "shardId-000000000000:49583841783469136626947675794180856103183100390328500226",
    "eventName": "aws:kinesis:record",
    "invokeIdentityArn": "arn:aws:iam::294557341534:role/lambda_firehoseTranformer",
    "awsRegion": "eu-central-1",
    "eventSourceARN": "arn:aws:kinesis:eu-central-1:294557341534:stream/test"
}
```

Is this expected behavior? If yes, please update the documentation. Using the sample test events and documentation for AWS Kinesis/Firehose and the AWS Kinesis-Lambda-Templates this does not work without a conversion back to JSON.

**Comment by MacInnis** [comment]
This is expected behavior.  The AWS SDK for JavaScript (used in this project) automatically base64-encodes the data before it sends it to Kinesis Data Streams or Kinesis Data Firehose.  The API documentation for Kinesis Data Streams mentions that input data should be base64-encoded:  https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecord.html  

Data consumers need to base64 decode the data to obtain the original record.  This is mentioned in the example in this documentation:  https://docs.aws.amazon.com/streams/latest/dev/fundamental-stream.html
